name: Java CI

on:
  push:
    branches:
      - main
      - 'release/**'
jobs:
  prep:
    runs-on: ubuntu-latest
    outputs:
      rev: ${{ steps.shortrev.outputs.rev }}
      ver: ${{ steps.pversion.outputs.ver }}
      date: ${{ steps.date.outputs.date }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8 & run tests & generate artifacts
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 8
          overwrite-settings: false
      - id: date
        run: echo "::set-output name=date::$(date +'%y%m%d' | cut -c 2-)"
      - id: shortrev
        run: echo ::set-output name=rev::$(git rev-parse --short HEAD)
      - id: pversion
        run: echo ::set-output name=ver::$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout| sed -e 's/-SNAPSHOT//g')
  versiongenerate:
    runs-on: ubuntu-latest
    needs: prep
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - id: version
        run: echo ::set-output name=version::${{ needs.prep.outputs.ver }}-${{ needs.prep.outputs.date }}-${{ needs.prep.outputs.rev }}
  build:
    runs-on: ubuntu-latest
    needs: versiongenerate
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8 & run tests & generate artifacts
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 8
          overwrite-settings: false
      - name: Version set
        run: mvn versions:set versions:commit -DnewVersion=${{ needs.versiongenerate.outputs.version }}
      - name: Build and test with Maven
        run: mvn clean install
      - name: PMD check
        run: mvn pmd:check
      - id: getfilename
        run: echo "::set-output name=file::$(ls target/symphony-dal-infrastructure-management-sembient-sembient-${{ needs.versiongenerate.outputs.version }}.jar)"
      - uses: actions/upload-artifact@v1
        with:
          name: SembientAggregatorCommunicator
          path: ${{ steps.getfilename.outputs.file }}